nginx:
  image: nginx:1.9
  ports:
    - '443:443'
  links:
    - registry:registry
    - gogs:gogs
  volumes:
    - /opt/nginx/conf:/etc/nginx/conf.d:ro
    - /opt/nginx/etc:/opt/nginx:ro
    - /opt/nginx/www:/opt/nginx/www:rw
gogs:
  image: gogs/gogs
  ports:
    - '8022:22'
    - '127.0.0.1:8030:3000'
  volumes:
    - /opt/gogs:/data:rw
registry:
  image: registry:2
  ports:
    - '127.0.0.1:5000:5000'
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - /opt/registry:/data
