FROM ctrlaltreboot/developer

MAINTAINER ctrlaltreboot "ctrlaltreboot@gmail.com"

RUN mkdir -p /opt/nodejs
RUN curl -s http://nodejs.org/dist/v0.10.28/node-v0.10.28-linux-x64.tar.gz | tar -v -C /opt/nodejs --strip-components=1 -xz
RUN curl https://npmjs.org/install.sh | clean=no sh
