web:
  image: dock1.rebooter.xyz/vh-report-service-web:latest
  ports:
   - "5555:5555"
  links:
   - mysql
   - activemq
  container_name: report-service-web
  environment:
   - "SPRING_PROFILES_ACTIVE=local"
   - "SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/vh_report_service"
   - "SPRING_DATASOURCE_USERNAME=ssuser"
   - "SPRING_DATASOURCE_PASSWORD=stay!up"
   - "SERVER_PORT=5555"
   - "SERVER_CONTEXT-PATH=/vh-report-service"
   - "SECURITY_USER_NAME=vh-report-user"
   - "SECURITY_USER_PASSWORD=VHR-s3rvic3s"
   - "SPRING_ACTIVEMQ_BROKER-URL=tcp://activemq:61616"
   - "SPRING_ACTIVEMQ_USER=admin"
   - "SPRING_ACTIVEMQ_PASSWORD=admin"
   - "QUEUE_REPORT_ORDER=QUEUE.ReportService.ReportOrder"
   - "SCHEDULER_INTERVAL=60000"
  labels:
    app: report-service-web
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: location=sg-dc
    io.rancher.scheduler.affinity:host_label: servername=morty

generator:
  image: dock1.rebooter.xyz/vh-report-service-generator:latest
  links:
     - mysql
     - activemq
  container_name: report-service-generator
  environment:
     - "SPRING_PROFILES_ACTIVE=local"
     - "SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/vh_report_service"
     - "SPRING_DATASOURCE_USERNAME=ssuser"
     - "SPRING_DATASOURCE_PASSWORD=stay!up"
     - "SPRING_ACTIVEMQ_BROKER-URL=tcp://activemq:61616"
     - "SPRING_ACTIVEMQ_USER=admin"
     - "SPRING_ACTIVEMQ_PASSWORD=admin"
     - "SPRING_FREEMARKER_PREFER-FILE-SYSTEM-ACCESS=false"
     - "SPRING_FREEMARKER_TEMPLATE-LOADER-PATH=classpath:/templates/freemarker"
     - "IMPALA_JDBC_DRIVER=com.amazon.impala.jdbc4.Driver"
     - "IMPALA_JDBC_URL=jdbc:impala://127.0.0.1:21050/;auth=noSasl"
     - "QUEUE_REPORT_ORDER=QUEUE.ReportService.ReportOrder"
     - "QUEUE_EMAIL_DELIVER=QUEUE.MailService.EmailDelivery"
     - "AWS_REGION=us-east-1"
     - "AWS_CREDENTIALS_ACCESS-KEY=hahahaha"
     - "AWS_CREDENTIALS_SECRET-KEY=hahahaha"
     - "AWS_S3_BUCKET-NAME=report-service-dev"
     - "AWS_SERVER_TIMEZONE=America/New_York"
  labels:
    app: report-service-web
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: location=sg-dc
    io.rancher.scheduler.affinity:host_label: servername=morty

mail-service:
  image: tsagitatremor/vh-mail-service:latest
  links:
   - activemq
   - smtp
  container_name: vh-mail-service
  environment:
   - "SPRING_PROFILES_ACTIVE=local"
   - "SPRING_ACTIVEMQ_BROKER-URL=tcp://activemq:61616"
   - "SPRING_ACTIVEMQ_USER=admin"
   - "SPRING_ACTIVEMQ_PASSWORD=admin"
   - "SPRING_MAIL_DEFAULT-ENCODING=UTF-8"
   - "SPRING_MAIL_PORT=25"
   - "SPRING_MAIL_HOST=smtp"
   - "QUEUE_EMAIL_DELIVER=QUEUE.MailService.EmailDelivery"
   - "QUEUE_EMAIL_DEADLETTER=QUEUE.MailService.DeadLetter"
  labels:
    app: vh-mail-service
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: location=sg-dc
    io.rancher.scheduler.affinity:host_label: servername=morty

mysql:
  image: mysql:5.6.28
  ports:
   - "3306:3306"
  environment:
   - "MYSQL_ROOT_PASSWORD=dr@gonb@ll"
   - "MYSQL_USER=ssuser"
   - "MYSQL_PASSWORD=stay!up"
   - "MYSQL_DATABASE=vh_report_service"
  container_name: report-service-db
  labels:
    app: report-service-db
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: location=sg-dc
    io.rancher.scheduler.affinity:host_label: servername=morty

activemq:
  image: tsagitatremor/activemq:5.13.0
  ports:
     - "8161:8161"
     - "61616:61616"
  container_name: report-service-activemq
  labels:
    app: report-service-activemq
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: location=sg-dc
    io.rancher.scheduler.affinity:host_label: servername=morty

smtp:
  image: namshi/smtp:latest
  ports:
   - "25:25"
  container_name: smtp-server
  environment:
   - "SES_USER=hahahaha"
   - "SES_PASSWORD=hahahaha"
  labels:
    app: report-service-smtp
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: location=sg-dc
    io.rancher.scheduler.affinity:host_label: servername=morty
