# ctrlaltreboot's docker file

# Base source, I prefer LTS
FROM ubuntu:12.04

MAINTAINER ctrlaltreboot "ctrlaltreboot@gmail.com"

# Freshen
RUN apt-get -y update
RUN apt-get install -y upstart wget curl git-core openssh-server build-essential wget curl libcurl3 libcurl3-gnutls libcurl4-openssl-dev libsqlite3-dev libpq-dev libmysqlclient-dev imagemagick libmagickwand-dev libmagickcore-dev libyaml-dev openssl libreadline6-dev update-motd man-db ssh git-core nano vim screen libxml2-dev libxslt1-dev upstart ntp unzip net-tools tmux
